---
title: "Green lab"
output: html_notebook
---
```{r}

# install packages
install.packages("ggplot2")
install.packages("xts")

library("ggplot2")
library("xts")
```

```{r}

# install packages for ARIMA
install.packages('forecast', dependencies = TRUE)
require("forecast")

```


```{r}

ank_s <- subset(ank, select=c("Release", "Value"))
ank_s
ank_df <- aggregate(ank_s[-1], list(ank_s$Release), FUN = mean, na.rm = TRUE)
ank_df
```

```{r}
# select only second and third columns
uhabit_s <- subset(uhabit, select=c("release", "value"))
uhabit_s

wifi_s <- subset(wifianalyzer, select=c("release", "value"))
wifi_s

ank_s <- subset(ankidroid, select=c("release", "value"))
ank_s


#create dataframe by aggregating the values - find mean value according to the release

wifi_df <- aggregate(wifi_s[-1], list(wifi_s$release), FUN = mean, na.rm = TRUE)
wifi_df

uhabit_df <- aggregate(uhabit_s[-1], list(uhabit_s$release), FUN = mean, na.rm = TRUE)
uhabit_df

ank_df <- aggregate(ank_s[-1], list(ank_s$release), FUN = mean, na.rm = TRUE)
ank_df


```



```{r}
# calculate 2 * standard deviation for all the apps
sd_wifi = 2.0 * sd(wifi_df$value)
sd_and = 2.0 * sd(ank_df$value)
sd_uhabit = 2.0 * sd(uhabit_df$value)
#print
sd_wifi 
sd_and 
sd_uhabit
```

```{r}

# rename columns
colnames(ank_df) <- c('Release','Value')

# draw a plot with smoothing line 
ank_df$Release <- factor(ank_df$Release, levels=ank_df$Release)

ggplot(data=ank_df, aes(x=Release, y=Value, group=1)) +
  geom_line(color="red") +
  ggtitle("Ankidroid") +
  theme(plot.title = element_text(hjust = 0.5)) +
  geom_smooth(method = "loess") + # show trend, loess() method is used 
  geom_point() 
  ggsave(file="Ankidroid.pdf", width=15, height=4, dpi=300) # save plot with a decent scale 


```


```{r}
# rename columns
colnames(wifi_df) <- c('Release','Value')

# draw a plot with smoothing line 

ggplot(data=wifi_df, aes(x=Release, y=Value, group=1)) +
  geom_line(color="red") +
  ggtitle("WiFi Analyzer") +
  theme(plot.title = element_text(hjust = 0.5)) +
  geom_smooth(method = "loess") + # show trend, loess() is used for less than 1,000 observations;
  geom_point()

```



```{r}
# rename columns
colnames(uhabit_df) <- c('Release','Value')

# draw a plot with smoothing line 
ggplot(data=uhabit_df, aes(x=Release, y=Value, group=1)) +
  geom_line(color="red") +
  ggtitle("Uhabit") +
  theme(plot.title = element_text(hjust = 0.5)) +
  geom_smooth(method = "loess") +  # show trend 
  geom_point()

```

Below an experimental part can be found. Those tests and results won't be used in the report (explained in detail in the paper itself)

```{r}
res_aov <- aov(value ~ release,
  data = wifi_s
)
res_aov
summary(res_aov)
```

```{r}
res_aov <- aov(value ~ release,
  data = ank_s
)
res_aov
summary(res_aov)
```


```{r}
res_aov <- aov(value ~ release,
  data = uhabit_s
)
res_aov
summary(res_aov)
```


```{r}
library(forecast)

ARIMAfit = auto.arima(log10(wifi_df$Value), approximation=FALSE,trace=FALSE)

summary(ARIMAfit)
predict(ARIMAfit,n.ahead = 5)
futurVal <- forecast(ARIMAfit,h=10, level=c(99.5))
plot(futurVal)
```










